---
title: Research
---

## Dissertation

"Knowledge and processing of morphosyntactic variation in African American Language and Mainstream American English" (Download [here](Maher2023_Dissertation.pdf))

## Manuscripts

Maher, Z., C. Blomquist, A. Byrd, K. Oppenheimer, E. Terrell Shockley, T.C. Thonesevanh, C. Mazzei, J. Harring, and J. Edwards (under revision). Does a dialect-shifting curriculum help early readers who speak African American English? Results from a randomized controlled study. 


## Publications

Maher, Z., C. Mazzei, T.C. Thonesevanh, E. Terrell Shockley, and J. Edwards (in press). [Multiple approaches to "appropriateness": A mixed-methods study of elementary teachers’ dispositions toward African American Language as they teach a dialect-shifting curriculum.](https://ila.onlinelibrary.wiley.com/doi/10.1002/rrq.554) *Reading Research Quarterly*.

Maher, Z., Erskine, M., Byrd, A., Harring, J., & Edwards, J. (2021). [African American English and early literacy: A comparison of approaches to quantifying nonmainstream dialect use](https://pubs.asha.org/doi/abs/10.1044/2020_LSHSS-19-00115). *Language, Speech, and Hearing Services in Schools, 52*(1), 118-130.

## Presentations

Maher, Z., J. Edwards, and J. Novick (2023). Morphosyntax plays a unique role in listeners’ expectations about minoritized language. Annual Conference on Human Sentence Processing. University of Michigan. Ann Arbor, MI.

Maher, Z., J. Edwards, and J. Novick (2023). Real-time interpretation of morphosyntactic variation across varieties and listeners. New Ways of Analyzing Variation. New York, NY.

Maher, Z., J. Edwards, and J. Novick (2023). They know who speak this way: Knowledge of variation in listeners with different experiences of African American Language. Annual Conference on Human Sentence Processing. University of Pittsburgh. Pittsburgh, PA. **Honorable Mention: Gibson/Fedorenko Prize for young scholars.**

Maher, Z., J. Edwards, and J. Novick (2023). Knowledge of variation in subject-verb agreement in speakers of Mainstream American English. American Dialect Society Annual Meeting. Denver, CO.

Maher, Z., C. Mazzei, T.C. Thonesevanh, E. Terrell Shockley, and J. Edwards (2022). Exploring Academic Spaces for Equitable Practices: Elementary Educator Dispositions Toward African American Language. American Educational Research Association 2022 Annual Meeting. San Diego, CA. https://doi.org/10.3102/1894097

Maher, Z., C. Mazzei, T.C. Thonesevanh, E. Terrell Shockley, and J. Edwards (2021). How a dialect-shifting curriculum shapes K-1 teachers’ attitudes toward language variation: A mixed-methods study. Language, Linguistics, and Life Conference. Temple University, Philadelphia, PA.

Erskine, M., A. Byrd, Z. Maher, K. Oppenheimer, and J. Edwards (2019). "Expanding your Toolbox: Strategies to Support Linguistically Diverse Students." ASHA Convention. Orlando, FL. 

Maher, Z. and Edwards, J. (2019). "Non-linguistic inhibition predicts lexical inhibition in 6-7 year-old children." Boston University Conference on Language Development. Boston, MA.

Huang, N., Z. Maher, S. Matyiku and R. Zanuttini (2011). "Toward an atlas of micro-syntactic variation in varieties of English." LSA Annual Meeting, Pittsburgh, PA.

## Posters

Maher, Z., J. Edwards, and J. Novick (2023). Real-Time Grammatical Interpretation Across Dialects and Listeners. Psychonomic Society Annual Meeting. San Francisco, CA.

Maher, Z., J. Edwards, and J. Novick (2022). They Was Giving Accurate Judgments: Speakers of Mainstream American English Show Partial Knowledge of Non-Mainstream Grammar. Psychonomic Society Annual Meeting. Boston, MA. 
Byrd, A., Z. Maher, Y.T. Huang, and J. Edwards (2022). Development and Evaluation of a Dialect Experience Questionnaire. Linguistic Society of America Annual Meeting, Washington, D.C.

Maher, Z., J. Edwards, and J. Novick (2021). Comprehenders reduce their reliance on subject-verb agreement when interpreting a less-familiar dialect. Psychonomic Society Annual Meeting. New Orleans, LA (virtual).

Maher, Z., J. Edwards, and J. Novick (2021). Dialect differences in the comprehension of agreement in U.S. varieties of English. Architectures and Mechanisms for Language Processing. Paris, France (virtual).

Maher, Z., Erskine, M., Byrd, A., & Edwards, J. (2021). Evaluating the influence of peers on the acquisition of mainstream forms by children who speak African American English. Variation in Language Acquisition. Rorschach, Switzerland.

Maher, Z. and Edwards, J. (2019). Changes in attitudes toward variation in teachers of a code-switching curriculum. New Ways of Analyzing Variation. Eugene, OR. ([View materials](https://umd.app.box.com/s/i6t0rcx0pgqgf7irhkeov002ccdmhxi4))

Erskine, M., Z. Maher, and J. Edwards (2019). "Dialect mismatch influences sentence *not* lexical comprehension in young children." Symposium for Research in Child Language Disorders. 